// Date: 01/09/2012 6:08:49 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package tco.daemon.core.client.render;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelGateway extends ModelBase {
	// fields
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape1;
	ModelRenderer Shape4;

	public ModelGateway() {
		textureWidth = 128;
		textureHeight = 64;

		Shape2 = new ModelRenderer(this, 0, 0);
		Shape2.addBox(-16F, -24F, 0F, 32, 4, 1);
		//Shape2.setRotationPoint(0F, 0F, 0F);
		Shape2.setTextureSize(128, 64);
		//Shape2.mirror = true;
		//setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 0, 0);
		Shape3.addBox(-16F, 16F, 0F, 32, 4, 1);
		//Shape3.setRotationPoint(0F, 0F, 0F);
		Shape3.setTextureSize(128, 64);
		//Shape3.mirror = true;
		//setRotation(Shape3, 0F, 0F, 0F);
		Shape1 = new ModelRenderer(this, 0, 5);
		Shape1.addBox(-16F, -20F, 0F, 4, 36, 1);
		Shape1.setRotationPoint(0F, 0F, 0F);
		Shape1.setTextureSize(128, 64);
		//Shape1.mirror = true;
		//setRotation(Shape4, 0F, 0F, 0F);
		Shape4 = new ModelRenderer(this, 0, 5);
		Shape4.addBox(12F, -20F, 0F, 4, 36, 1);
		//Shape4.setRotationPoint(0F, 0F, 0F);
		Shape4.setTextureSize(128, 64);
		//Shape4.mirror = true;
		//setRotation(Shape4, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float x, float y, float z, float rx,
			float ry, float rz) {
		super.render(entity, x, y, z, rx, ry, rz);
		setRotationAngles(x, y, z, rx, ry, rz);
		Shape2.render(rz);
		Shape3.render(rz);
		Shape1.render(rz);
		Shape4.render(rz);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
